ModelBindingAPI_MVC/Controllers/ModelBindingController.cs
using ModelBinding_11168.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ModelBindingAPI_MVC.Controllers
{
    public class ModelBindingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SimpleBinding(string Name, int Age)
        {
            try
            {
                 return Content(nameof(Name) + ":" + Name + ", " + nameof(Age) + ":" + Age); } catch (Exception ex) { return Content(ex.Message); }
        }
        public ActionResult ModelBindObj(Human data)
        {
            if (data.Age != 0 && !string.IsNullOrEmpty(data.Name)) { return Json(data);} else {return Json("Null" );  }
        }
        public ActionResult SimpleModelBindArray(string[] Name, int[] Age)
        {        if (Name != null)
            {
                try
                {
                    List<string> listName = new List<string>();
                    List<int> listAge = new List<int>();
                    foreach (string s in Name)
                    {
                        if (!string.IsNullOrEmpty(s))
                        {
                            listName.Add(s);
                        }
                    }
                    foreach (int age in Age)
                    {
                        if (age != 0)
                        {
                            listAge.Add(age);
                        }
                    }
                    int countName = listName.Count();
                    int countAge = listAge.Count();
                    if (countName == 0 && countAge == 0)
                    {
                        return Content("Null");
                    }
                    else
                    {
                        string str = nameof(Name) + ":";
                        foreach (string n in Name)
                        {
                            str += n + ",";
                        }
                        str = str.Substring(0, str.Length - 1);
                        str += " | ";
                        str += nameof(Age) + ":";
                        foreach (int a in Age)
                        {
                            str += a + ",";
                        }
                        str = str.Substring(0, str.Length - 1);
                        return Content(str);
                    }
                }
                catch (Exception ex)
                {
                    return Content(ex.Message);
                }
            }
            else { return Content("ObjectNotExist"); }
        }
        public ActionResult ModelBindingArray(Human[] data)
        {
            return Json(data);
        }
        public ActionResult ModelBindingNestedObj(Person data)
        {
            return Json(data);
        }
        public ActionResult ModelBindingArrayNestedObj(Person[] data)
        {
            return Json(data);
        }
        public ActionResult FileUpload() {
            return View();
        }
    }
}

ModelBindingAPI_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {font-size:2em;
              color:black;
        }
  .container {padding:5px;
                    margin:5px;
                    width:100%;
                    background-color:transparent;
        }
    .container body-content {
        width: 100%;
    }
        .navbar-inverse {
            background-color:aqua;
            border:1px solid yellow;
            color:black;

        }
</style>
</head>
<body>
    <hr />
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ModelBinding_11168", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("MVC_ModelBinding", "Index", "ModelBinding", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("API", "API", "Home", new { area = "" }, null)</li>*@
                    <li>@Html.ActionLink("API_ModelBinding", "APIModelBinding", "Home", new { area = "" }, null)</li>

                    <li>@Html.ActionLink("FileUpload", "FileUpload", "ModelBinding", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>